name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request: ~
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # pin@v4.0.0
        with:
          go-version: 1.20
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@07db5389c99593f11ad7b44463c2d4233066a9b1 # pin@v3.3.0
        with:
          version: v1.52.2
          args: --verbose --timeout 5m
