name: gardenlogin-updater

on:
  release:
    types:
      - published
jobs:
  update_gardenlogin_in_homebrew_tap_and_chocolatey_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - name: Build the binary-files
        id: build_binary_files
        run: |
          sudo apt-get update
          sudo apt-get install make -y
          make build
          echo ::set-output name=latest_release_filtered_tag::${GITHUB_REF##*/}
      - name: Upload binaries to release
        uses: AButler/upload-release-assets@ec6d3263266dc57eb6645b5f75e827987f7c217d # pin@v2.0
        with:
          files: 'bin/darwin-amd64/gardenlogin_darwin_amd64;bin/linux-amd64/gardenlogin_linux_amd64;bin/windows-amd64/gardenlogin_windows_amd64.exe'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.build_binary_files.outputs.latest_release_filtered_tag }}
      - name: Get token for gardener-github-pkg-mngr app
        id: gardener-github-workflows
        uses: getsentry/action-github-app-token@8f656f2b31c7aaef91ba5cfdbe308d2a4d72e4f4 # pin@v1
        with:
          app_id: ${{ secrets.GARDENER_GITHUB_WORKFLOW_PKG_MNGR_APP_ID }}
          private_key: ${{ secrets.GARDENER_GITHUB_WORKFLOW_PKG_MNGR_APP_PRIVATE_KEY }}
      - name: Send update with latest versions to gardener/homebrew-tap
        run: |
          darwin_sha256sum_amd64=$(sha256sum bin/darwin-amd64/gardenlogin_darwin_amd64 | awk '{print $1}')
          darwin_sha256sum_arm64=$(sha256sum bin/darwin-arm64/gardenlogin_darwin_arm64 | awk '{print $1}')
          linux_sha256sum_amd64=$(sha256sum bin/linux-amd64/gardenlogin_linux_amd64 | awk '{print $1}')
          data='{"event_type": "update", "client_payload": { "component": "gardenlogin", "tag": "'"${{ steps.build_binary_files.outputs.latest_release_filtered_tag }}"'", "darwin_sha_amd64": "'"$darwin_sha256sum_amd64"'", "darwin_sha_arm64": "'"$darwin_sha256sum_arm64"'", "linux_sha_amd64": "'"$linux_sha256sum_amd64"'"}}'
          echo "${data}"
          curl -X POST https://api.github.com/repos/gardener/homebrew-tap/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H "Authorization: Token ${{ steps.gardener-github-workflows.outputs.token }}" \
          --data "${data}"
      - name: Send update with latest versions to gardener/chocolatey-packages
        run: |
          windows_sha256sum=$(sha256sum bin/windows-amd64/gardenlogin_windows_amd64.exe | awk '{print $1}')
          data='{"event_type": "update", "client_payload": { "component": "gardenlogin", "tag": "'"${{ steps.build_binary_files.outputs.latest_release_filtered_tag }}"'", "windows_sha": "'"$windows_sha256sum"'"}}'
          echo "${data}"
          curl -X POST https://api.github.com/repos/gardener/chocolatey-packages/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H "Authorization: Token ${{ steps.gardener-github-workflows.outputs.token }}" \
          --data "${data}"

